// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjE-N7UpSnreiK0wppz_v8w36-sV9mFYk',
    appId: '1:660594970419:web:99e051bd73a9098066f846',
    messagingSenderId: '660594970419',
    projectId: 'vu-community-app',
    authDomain: 'vu-community-app.firebaseapp.com',
    storageBucket: 'vu-community-app.appspot.com',
    measurementId: 'G-5XY00FBLL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtVcBB7cmO-1wvnm7KLTDlY7lvI66AJZs',
    appId: '1:660594970419:android:176ab3d502ea0c2566f846',
    messagingSenderId: '660594970419',
    projectId: 'vu-community-app',
    storageBucket: 'vu-community-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_pm__X0lTryAv0AzVAIMXh3hQFm2ME20',
    appId: '1:660594970419:ios:6acc205c9282d3aa66f846',
    messagingSenderId: '660594970419',
    projectId: 'vu-community-app',
    storageBucket: 'vu-community-app.appspot.com',
    iosBundleId: 'com.example.vuHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_pm__X0lTryAv0AzVAIMXh3hQFm2ME20',
    appId: '1:660594970419:ios:6acc205c9282d3aa66f846',
    messagingSenderId: '660594970419',
    projectId: 'vu-community-app',
    storageBucket: 'vu-community-app.appspot.com',
    iosBundleId: 'com.example.vuHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjE-N7UpSnreiK0wppz_v8w36-sV9mFYk',
    appId: '1:660594970419:web:5dd5a73a14a4c5f766f846',
    messagingSenderId: '660594970419',
    projectId: 'vu-community-app',
    authDomain: 'vu-community-app.firebaseapp.com',
    storageBucket: 'vu-community-app.appspot.com',
    measurementId: 'G-L5B7DJYEK9',
  );
}
